### ISSUE TITLE
SassDoc support

### ISSUE THREAD

**Issue by nagman** [wkillerud/vscode-scss#60]
Great extension! The `@use` intellisense and the SassDoc `@params` enums are my two favorite features.

Yet it is not clear in the README what SassDoc annotations are supported.

For instance, `@name` is not implemented, `@group` neither.

So far, I've only seen `@author`, `@type` and `@params` to be implemented.

There's also no documentation on how to implement enums in params, so I leave it here for anyone struggling to find it:
```sass
/// @param {"option1" | "option2" | "option3"} $option -
@mixin foobar($option) {
  ...
}
```
The double quotes are important or else the intelissense won't be triggered.

PS: I'm sorry that is not an issue but there's no "Discussion" type for this kind of question.

**Comment by wkillerud** [comment]
That's odd, I thought [this list of annotations](https://github.com/wkillerud/vscode-scss/blob/main/server/src/features/sassdoc-annotations.ts) all worked. All [documented SassDoc annotations](http://sassdoc.com/annotations/) _should_ work, so if they don't that's a bug.

I don't remember right now _why_ the double quotes are required (it's been a while since I looked at that part of the code). Might be a limitation in the parser. I'd have to dig around.

Like I mentioned, I'm a bit busy these coming weeks. I might look into this at a later date.

Glad you like the extension, and thanks for dropping the tip about enums :)

**Comment by wkillerud** [comment]
I looked into the problem with SassDoc annotations not showing automatically, and it's not something I'll be able to fix. The short explanation is I would need to change some parts of the language definition in VS Code, which is... _complicated_.

A workaround is to [manually ask for code suggestions with `Ctrl + Space`](https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features).

https://github.com/wkillerud/vscode-scss/assets/1223410/b86f68d3-d9d5-4e1f-86b3-0b727ea42035

**Comment by nagman** [comment]
Oh, I may have wrongly explained: I don't have an issue with the autocomplete of attributes, but with showing info on mixins and variables that have been tagged.

Example:
_
```scss
/// @access public
/// @author beebop
/// @deprecated
/// @example scss
/// 	@include colorize(blue);
/// @group helpers
/// @link https://some.url
/// @name primary-color-util
/// @param {Color} $color [red] - color used
/// @output prints the primary color (or custom) in the color attribute
@mixin colorize($color: red) {
	color: $color;
}

/// @name primary-color
/// @group helpers
/// @type Color
$red: red;
```

The tooltips are then:
<img width="406" alt="image" src="https://github.com/wkillerud/vscode-scss/assets/16116486/db0ff911-bd79-45eb-a227-8b81ed191564">

<img width="408" alt="image" src="https://github.com/wkillerud/vscode-scss/assets/16116486/578c75ce-b2a0-4692-9ed3-787b8ee7024d">

The following attributes don't show up:
- @access
- @group
- @name

The @deprecated is only showed once the variable or mixin has been fully typed:
<img width="254" alt="image" src="https://github.com/wkillerud/vscode-scss/assets/16116486/c9f2e7d6-b44a-4d30-a4ad-1871bfe97e73">
(this is great to have this striked out, by the way)
